###
GET http://localhost:7000/products

###
GET http://localhost:7000/...

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "user1@mail.com",
  "firstName": "Alphie",
  "lastName": "Bravo",
  "password": "password123"
}

###

POST http://localhost:7000/auth
Content-Type: application/json

{
  "email": "user1@mail.com",
  "firstName": "Alphie",
  "lastName": "Bravo",
  "password": "password123"
}